var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(c,a.prototype);return c};var Point=function(){};
Point.getRandomPoint=function(a,b){return{x:Math.floor(Math.random()*a),y:Math.floor(Math.random()*b)}};Point.getNeighborPoints=function(a,b,c){for(var d=[],e=a.y-1;e<=a.y+1;e++)for(var f=a.x-1;f<=a.x+1;f++)0<=f&&f<b&&0<=e&&e<c&&(f!=a.x||e!=a.y)&&d.push({x:f,y:e});return d};Point.distance=function(a,b){return Math.pow(a.x-b.x,2)+Math.pow(a.y-b.y,2)};Point.toString=function(a){return a.x+"_"+a.y};var SquareState;
(function(a){a[a.Unknown=0]="Unknown";a[a.Flagged=1]="Flagged";a[a.Question=2]="Question";a[a.Revealed=3]="Revealed"})(SquareState||(SquareState={}));function isUnknownOrQuestion(a){return a==SquareState.Unknown||a==SquareState.Question}var EMPTY=0,MINE=-1,CALL_LIMIT=Math.pow(2,12),SHUFFLE_LIMIT=Math.pow(2,14);
function logProbabilityMap(a){var b=[].concat($jscomp.arrayFromIterable(a.entries())).map(function(a){var c=$jscomp.makeIterator(a);a=c.next().value;c=c.next().value;return a.name+"::"+c}).join("\n\t");console.log("Permutations: ("+a.__permutations+") in "+a.__recursiveCalls+" calls \n\t"+b)}var Square=function(a,b){this.value=a;this.point=b;this.neighbors=new Set;this.name=Point.toString(this.point);this.state=SquareState.Unknown;this.highlight=!1};
Square.prototype.toJSON=function(){return{value:this.value,state:this.state,highlight:this.highlight}};
var MineSweeper=function(a,b,c,d,e,f){var g=this;this.width=a;this.height=b;this.mines=c;this.luck=void 0===d?!0:d;this.emptyFirstTap=void 0===e?!0:e;this.randomHints=void 0===f?!0:f;this.squares=new Map;this.lastTapPoint={x:0,y:0};this.init=function(){var a=!1;return function(c){if(a)throw Error("Already initialized!");a=!0;g.lastTapPoint=c;c=g.squares.get(Point.toString(c));if(!c)throw Error("Invalid starting position!");c=new Set([c].concat($jscomp.arrayFromIterable(g.emptyFirstTap?c.neighbors:
[])));for(var b=0;b<g.mines;){var d=g.squares.get(Point.toString(Point.getRandomPoint(g.width,g.height)));d&&!c.has(d)&&d.value!=MINE&&(b++,g.addMine(d))}}}();this.lastHint=void 0;this.cantBeMines=new Set;this.mustBeMines=new Set;if(1>c||c>=a*b-9||1>a||1>b)throw Error("Invalid starting game configuration!");for(c=0;c<b;c++)for(d=0;d<a;d++)this.squares.set(Point.toString({x:d,y:c}),new Square(EMPTY,{x:d,y:c}));for(c=0;c<b;c++)for(d={},e=0;e<a;d={$jscomp$loop$prop$square$16:d.$jscomp$loop$prop$square$16},
e++)d.$jscomp$loop$prop$square$16=this.squares.get(Point.toString({x:e,y:c})),Point.getNeighborPoints({x:e,y:c},a,b).map(function(a){return g.squares.get(Point.toString(a))}).forEach(function(a){return function(c){return a.$jscomp$loop$prop$square$16.neighbors.add(c)}}(d))};
MineSweeper.prototype.flag=function(a){"playing"==this.status()&&(this.lastTapPoint=a,(a=this.squares.get(Point.toString(a)))&&a.state!=SquareState.Revealed&&(a.highlight=!1,a==this.lastHint&&(this.lastHint=void 0),a.state=a.state==SquareState.Unknown?SquareState.Flagged:SquareState.Unknown))};
MineSweeper.prototype.tap=function(a){var b=this;if("playing"==this.status()&&(this.lastTapPoint=a,a=this.squares.get(Point.toString(a)))){if(a.state==SquareState.Revealed){if(0<a.value){var c=[].concat($jscomp.arrayFromIterable(filter(a.neighbors,function(a){return a.state!=SquareState.Revealed}))),d=count(c,function(a){return a.state==SquareState.Flagged});0==count(c,function(a){return a.state==SquareState.Question})&&d==a.value&&forEach(filter(c,function(a){return a.state==SquareState.Unknown}),
function(a){return b.reveal(a)})}}else a.state==SquareState.Flagged?a.state=SquareState.Question:a.state==SquareState.Question?a.state=SquareState.Flagged:a.state==SquareState.Unknown&&(this.luck&&this.tryLuck(a),this.reveal(a));"win"==this.status()&&this.squares.forEach(function(a){a.state==SquareState.Unknown&&a.value==MINE&&(a.state=SquareState.Flagged)})}};
MineSweeper.prototype.getBoard=function(){for(var a=[],b=0;b<this.height;b++){a[b]=[];for(var c=0;c<this.width;c++)a[b][c]=this.squares.get(Point.toString({x:c,y:b})).toJSON()}return a};MineSweeper.prototype.getGameState=function(){return{status:this.status(),mines:this.minesRemaining()}};
MineSweeper.prototype.prettyPrint=function(){return this.getBoard().map(function(a){return a.map(function(a){return a.state==SquareState.Unknown?"\u25a0":a.state==SquareState.Flagged?"\u0192":a.state==SquareState.Question?"?":a.value==MINE?"*":a.value==EMPTY?" ":a.value.toString()}).join("")}).join("\n")};
MineSweeper.prototype.hint=function(){if(this.lastHint)return[this.lastHint.point];var a=this.simpleHint();if(a.length)return a.map(function(a){return a.point});try{var b=$jscomp.makeIterator(this.calculateProbs()).next().value,c=this.advancedHint();if(c.length)return[c[0].point];var d=[].concat($jscomp.arrayFromIterable(filter(filter(shuffle([].concat($jscomp.arrayFromIterable(b.entries()))).sort(function(a,c){var b=$jscomp.makeIterator(a);b.next();b=b.next().value;var d=$jscomp.makeIterator(c);
d.next();d=d.next().value;return b-d}),function(a){return $jscomp.makeIterator(a).next().value.state!=SquareState.Revealed}),function(a){return a[0].value!=MINE})));if(d.length&&(this.luck||0==d[0][1]))return this.lastHint=d[0][0],[d[0][0].point];var e=this.randomHint();return e?[e.point]:void 0}catch(f){console.log(""+f)}a=this.advancedHint();return a.length?[a[0].point]:(a=this.randomHint())?[a.point]:void 0};
MineSweeper.prototype.randomHint=function(){var a=this;if(this.randomHints){var b=shuffle([].concat($jscomp.arrayFromIterable(filter(filter(this.squares.values(),function(a){return a.state==SquareState.Unknown}),function(a){return!!find(a.neighbors.values(),function(a){return a.state!=SquareState.Unknown})})))).sort(function(c,b){var d=count(c.neighbors,function(a){return a.state==SquareState.Revealed});return 1E4*(count(b.neighbors,function(a){return a.state==SquareState.Revealed})-d)+Point.distance(c.point,
a.lastTapPoint)-Point.distance(b.point,a.lastTapPoint)})[0];if(b)return this.lastHint=b,console.log("Random Hint @ "+b.name),b.value==MINE?this.addMustBeMine(b):this.addCantBeMine(b),b}};
MineSweeper.prototype.simpleHint=function(){var a=this,b=this.incorrectlyFlagged();if(b.length)return b.forEach(function(a){a.state==SquareState.Flagged&&(a.highlight=!0)}),b;this.withObviousFlags(function(){});b=[].concat($jscomp.arrayFromIterable(this.nextObviousFlag()),$jscomp.arrayFromIterable(this.nextObviousTap()));return b.length?b.sort(function(c,b){return Point.distance(c[0].point,a.lastTapPoint)-Point.distance(b[0].point,a.lastTapPoint)})[0]:[]};
MineSweeper.prototype.advancedHint=function(){var a=this;return[].concat($jscomp.arrayFromIterable(filter(filter(this.mustBeMines.values(),function(a){return a.state!=SquareState.Flagged}),function(a){return a.state!=SquareState.Revealed})),$jscomp.arrayFromIterable(filter(this.cantBeMines.values(),function(a){return a.state!=SquareState.Revealed}))).sort(function(b,c){return Point.distance(b.point,a.lastTapPoint)-Point.distance(c.point,a.lastTapPoint)})};
MineSweeper.prototype.undo=function(){var a=this,b=find(this.squares.values(),function(a){return a.value==MINE&&a.state==SquareState.Revealed&&1==a.highlight});if(b){b.state=SquareState.Flagged;forEach(this.squares.values(),function(a){a.highlight=!1;a.state==SquareState.Revealed&&a.value==MINE&&(a.state=SquareState.Unknown)});this.addMustBeMine(b);try{this.calculateProbs()}catch(c){}finally{forEach(this.squares.values(),function(c){c.state==SquareState.Flagged&&(a.mustBeMines.has(c)||a.cantBeMines.has(c)?
a.cantBeMines.has(c)&&(c.highlight=!0):c.state=SquareState.Question)})}this.shuffle([].concat($jscomp.arrayFromIterable(filter(this.squares.values(),function(a){return a.state!=SquareState.Revealed}))))}};
MineSweeper.prototype.status=function(){for(var a=!1,b=$jscomp.makeIterator(this.squares),c=b.next();!c.done;c=b.next()){c=$jscomp.makeIterator(c.value);c.next();c=c.next().value;if(c.value==MINE&&c.state==SquareState.Revealed)return"lose";c.value!=MINE&&c.state!=SquareState.Revealed&&(a=!0)}return a?"playing":"win"};MineSweeper.prototype.minesRemaining=function(){return this.mines-count(this.squares.values(),function(a){return a.state==SquareState.Flagged})};
MineSweeper.prototype.reveal=function(a){a==this.lastHint&&(this.lastHint=void 0);a.value==MINE?(a.state=SquareState.Revealed,a.highlight=!0,this.squares.forEach(function(a){a.state!=SquareState.Revealed&&a.state!=SquareState.Flagged&&a.value==MINE&&(a.state=SquareState.Revealed);a.state==SquareState.Flagged&&a.value!=MINE&&(a.highlight=!0)})):(a.state=SquareState.Revealed,a.value==EMPTY&&this.revealNeighbors(a))};
MineSweeper.prototype.revealNeighbors=function(a){var b=this;a.neighbors.forEach(function(a){a.state!=SquareState.Revealed&&a.value!=MINE&&(a.state=SquareState.Revealed,a.value==EMPTY&&b.revealNeighbors(a))})};MineSweeper.prototype.addMine=function(a){a.value!=MINE&&(a.value=MINE,a.neighbors.forEach(function(a){0<=a.value&&a.value++}))};
MineSweeper.prototype.removeMine=function(a){a.value==MINE&&(a.value=count(a.neighbors,function(a){return a.value==MINE}),a.neighbors.forEach(function(a){0<a.value&&a.value--}))};
MineSweeper.prototype.incorrectlyFlagged=function(){for(var a=$jscomp.makeIterator(this.squares),b=a.next();!b.done;b=a.next())if(b=$jscomp.makeIterator(b.value),b.next(),b=b.next().value,b.state==SquareState.Revealed&&0<b.value&&count(b.neighbors,function(a){return a.state==SquareState.Flagged})>b.value)return[].concat($jscomp.arrayFromIterable(filter(b.neighbors,function(a){return a.state==SquareState.Flagged&&a.value!=MINE})));return[].concat($jscomp.arrayFromIterable(filter(this.squares.values(),
function(a){return a.state==SquareState.Flagged&&a.value!=MINE})))};
MineSweeper.prototype.nextObviousFlag=function(){for(var a=[],b=$jscomp.makeIterator(this.squares),c=b.next();!c.done;c=b.next())if(c=$jscomp.makeIterator(c.value),c.next(),c=c.next().value,c.state==SquareState.Revealed&&0<c.value){var d=count(c.neighbors,function(a){return a.state==SquareState.Flagged}),e=[].concat($jscomp.arrayFromIterable(filter(c.neighbors,function(a){return isUnknownOrQuestion(a.state)})));e.length&&e.length==c.value-d&&a.push(e)}return a};
MineSweeper.prototype.nextObviousTap=function(){for(var a=[],b=$jscomp.makeIterator(this.squares),c=b.next();!c.done;c=b.next())if(c=$jscomp.makeIterator(c.value),c.next(),c=c.next().value,c.state==SquareState.Revealed&&0<c.value){var d=count(c.neighbors,function(a){return a.state==SquareState.Flagged}),e=[].concat($jscomp.arrayFromIterable(filter(c.neighbors,function(a){return a.state==SquareState.Unknown})));d==c.value&&e.length&&a.push([c])}return a};
MineSweeper.prototype.withObviousFlags=function(a){var b=this;do{var c=this.mustBeMines.size+this.cantBeMines.size;forEach(this.squares.values(),function(a){return b.cacheSquareNeighbors(a)})}while(this.mustBeMines.size+this.cantBeMines.size>c);var d=[];[].concat($jscomp.arrayFromIterable(filter(this.squares.values(),function(a){return a.state!=SquareState.Revealed}))).forEach(function(a){if(a.state==SquareState.Flagged&&!b.mustBeMines.has(a))d.push(function(){return a.state=SquareState.Flagged}),
a.state=SquareState.Unknown;else if(b.mustBeMines.has(a)){var c=a.state;d.push(function(){return a.state=c});a.state=SquareState.Flagged}});try{return a()}finally{d.forEach(function(a){return a()})}};
MineSweeper.prototype.withEverythingElseRevealed=function(a,b){var c=new Set,d=function(a){c.has(a)||(c.add(a),a.neighbors.forEach(function(a){a.state!=SquareState.Revealed&&d(a)}))};d(a);var e=[];forEach(this.squares.values(),function(b){if(!c.has(b)&&b.state!=SquareState.Revealed)if(b.value==MINE){var d=a.state;e.push(function(){return a.state=d});a.state=SquareState.Flagged}else{var f=a.state;e.push(function(){return a.state=f});a.state=SquareState.Revealed}});try{return b()}finally{e.forEach(function(a){return a()})}};
MineSweeper.prototype.tryLuck=function(a){var b=this;a.value!=MINE||this.incorrectlyFlagged().length||this.withEverythingElseRevealed(a,function(){try{var c=$jscomp.makeIterator(b.calculateProbs()),d=c.next().value,e=c.next().value,f=d.get(a);d.__permutations&&f&&f<d.__permutations&&!e.find(function(a){return d.get(a)<f})&&b.shuffle(e,a)}catch(g){console.log(""+g)}})};
MineSweeper.prototype.shuffle=function(a,b){var c=this;this.withObviousFlags(function(){a=a.filter(function(a){return isUnknownOrQuestion(a.state)});var d=new Set(a.filter(function(a){return a.value==MINE})),e=d.size;if(0==e)console.log("It's impossible to shuffle this board!");else{var f=a,g=f.filter(function(a){return!!find(a.neighbors,function(a){return a.state==SquareState.Revealed})});console.log("Shuffling "+e+" mines from "+f.length+" with "+g.length+" edges");for(var h=new Set,k=g,m=0;m++<
SHUFFLE_LIMIT;){if(k.length&&(k=k.filter(function(a){return!h.has(a)&&c.couldBeAMine(a,h)}),!k.length&&h.size&&!c.couldBeValidGame(h))){h=new Set;k=g;continue}var l=k.length?k:f;l.length||console.log("Error!! "+g.length+" "+f.length);l=l[Math.floor(Math.random()*l.length)];b&&l==b||!c.couldBeAMine(l,h)||h.add(l);if(h.size==e)if(c.couldBeValidGame(h)){d.forEach(function(a){return c.removeMine(a)});h.forEach(function(a){return c.addMine(a)});break}else h=new Set,k=g}m>SHUFFLE_LIMIT?console.log("Failed to shuffle the board in "+
m+"/"+SHUFFLE_LIMIT+" loops"):console.log("Shuffle the board in "+m+"/"+SHUFFLE_LIMIT+" loops")}})};MineSweeper.prototype.couldBeValidGame=function(a){if(a.size>this.mines-this.mustBeMines.size)return!1;for(var b=$jscomp.makeIterator(this.squares),c=b.next();!c.done;c=b.next())if(c=$jscomp.makeIterator(c.value),c.next(),c=c.next().value,c.state==SquareState.Revealed&&c.value!=count(c.neighbors,function(c){return c.state==SquareState.Flagged||a.has(c)}))return!1;return!0};
MineSweeper.prototype.addCantBeMine=function(a){this.cantBeMines.has(a)||(a.value==MINE?console.log("TRIED TO ADD A MINE ("+a.name+") TO CANTBEMINES!!"):(this.cantBeMines.add(a),this.cacheSquareNeighbors(a)))};MineSweeper.prototype.addMustBeMine=function(a){this.mustBeMines.has(a)||(a.value!=MINE?console.log("TRIED TO ADD A NON-MINE ("+a.name+") TO MUSTBEMINES!!"):(this.mustBeMines.add(a),this.cacheSquareNeighbors(a)))};
MineSweeper.prototype.cacheSquareNeighbors=function(a){var b=this;a.state!=SquareState.Revealed||0>=a.value||forEach(filter(a.neighbors,function(a){return a.state==SquareState.Revealed}),function(a){var c=count(a.neighbors,function(a){return a.state!=SquareState.Revealed}),e=count(a.neighbors,function(a){return a.state!=SquareState.Revealed&&b.mustBeMines.has(a)}),f=count(a.neighbors,function(a){return a.state!=SquareState.Revealed&&b.cantBeMines.has(a)});a.value==e?forEach(filter(a.neighbors,function(a){return a.state!=
SquareState.Revealed&&!b.mustBeMines.has(a)}),function(a){return b.addCantBeMine(a)}):a.value==c-f-e+e&&forEach(filter(a.neighbors,function(a){return a.state!=SquareState.Revealed&&!b.mustBeMines.has(a)&&!b.cantBeMines.has(a)}),function(a){return b.addMustBeMine(a)})})};
MineSweeper.prototype.cacheProbs=function(a){var b=this;a.__permutations&&a.forEach(function(c,d){0==c&&b.addCantBeMine(d);c==a.__permutations&&b.addMustBeMine(d)});console.log("this.cantBeMines: "+this.cantBeMines.size);console.log("this.mustBeMines: "+this.mustBeMines.size)};
MineSweeper.prototype.calculateProbs=function(){var a=this;return this.withObviousFlags(function(){var b=[].concat($jscomp.arrayFromIterable(filter(a.squares.values(),function(a){return isUnknownOrQuestion(a.state)}))),c=a.mines-a.mustBeMines.size;12<b.length&&12<c&&(b=b.filter(function(a){return!!find(a.neighbors,function(a){return a.state==SquareState.Revealed})}),c=-1);var d=new Map;b.forEach(function(a){d.set(a,0)});a._calculateProbs(b,0,d,c,new Set);a.cacheProbs(d);logProbabilityMap(d);return[d,
b]})};
MineSweeper.prototype._calculateProbs=function(a,b,c,d,e){c.__recursiveCalls=(c.__recursiveCalls||0)+1;if(c.__recursiveCalls==CALL_LIMIT)throw Error("Too many recursive calls ("+CALL_LIMIT+") while calculating game state!\n\t(Found "+c.__permutations+" valid game permutations)");var f=a[b];f&&0!=d&&this.mines-this.mustBeMines.size!=e.size?(this.couldBeAMine(f,e)&&(e.add(f),this._calculateProbs(a,b+1,c,d-1,e),e["delete"](f)),this._calculateProbs(a,b+1,c,d,e)):(0>=d||this.mines-this.mustBeMines.size==e.size)&&
this.couldBeValidGame(e)&&(c.__permutations=(c.__permutations||0)+1,forEach(e,function(a){c.set(a,(c.get(a)||0)+1)}))};MineSweeper.prototype.couldBeAMine=function(a,b){if(b.has(a)||this.cantBeMines.has(a))return!1;if(this.mustBeMines.has(a))return!0;for(var c=$jscomp.makeIterator(a.neighbors),d=c.next();!d.done;d=c.next())if(d=d.value,d.state==SquareState.Revealed&&count(d.neighbors,function(a){return a.state==SquareState.Flagged||b.has(a)})>=d.value)return!1;return!0};
function filter(a,b){var c,d,e;return $jscomp.generator.createGenerator(filter,function(f){1==f.nextAddress&&(c=$jscomp.makeIterator(a),d=c.next());if(3!=f.nextAddress){if(d.done)return f.jumpTo(0);e=d.value;return b(e)?f.yield(e,3):f.jumpTo(3)}d=c.next();return f.jumpTo(2)})}function find(a,b){for(var c=$jscomp.makeIterator(a),d=c.next();!d.done;d=c.next())if(d=d.value,b(d))return d}function reduce(a,b,c){a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())c=b(c,d.value);return c}
function forEach(a,b){for(var c=$jscomp.makeIterator(a),d=c.next();!d.done;d=c.next())b(d.value)}function count(a,b){return reduce(a,function(a,d){return a+(b(d)?1:0)},0)}function shuffle(a){for(var b=a.length,c,d;0!==b;)d=Math.floor(Math.random()*b),--b,c=a[b],a[b]=a[d],a[d]=c;return a};